### ISSUE TITLE
[HANDS-ON BUG]  unit 3: cannot find dqn.yml file 

### ISSUE THREAD

**Issue by valleyh** [huggingface/deep-rl-class#390]
# Describe the bug

I am doing the hands-on of Unit 3. In section "Train our deep Q-learning agent to ply space Invaders", an error appeared  when I am running "!python -m rl_zoo3.train --algo dqn  --env SpaceInvadersNoFrameskip-v4 -f logs/ -c dqn.yml". It states that

"
Loading hyperparameters from: dqn.yml
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/rl_zoo3/train.py", line 274, in <module>
    train()
  File "/usr/local/lib/python3.10/dist-packages/rl_zoo3/train.py", line 256, in train
    results = exp_manager.setup_experiment()
  File "/usr/local/lib/python3.10/dist-packages/rl_zoo3/exp_manager.py", line 187, in setup_experiment
    hyperparams, saved_hyperparams = self.read_hyperparameters()
  File "/usr/local/lib/python3.10/dist-packages/rl_zoo3/exp_manager.py", line 291, in read_hyperparameters
    with open(self.config) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dqn.yml'
"
I found this dqn.yml file in the folder hyperparams/ and also I copied it from hyperparams/ to its upper folder rl_zoo3/, the error is still there. 

 I am wondering if anyone also met such problem? Can anyone help solve it? Thanks a lot.

 I am using Google Colab

**Comment by simoninithomas** [comment]
Hey there 👋 in this tutorial you need to create your own dqn.yml. "1. Create a hyperparameter config file that will contain our training hyperparameters called `dqn.yml`."

**Comment by simoninithomas** [comment]
## Train our Deep Q-Learning Agent to Play Space Invaders 👾

To train an agent with RL-Baselines3-Zoo, we just need to do two things:

1. Create a hyperparameter config file that will contain our training hyperparameters called `dqn.yml`.

This is a template example:

```
SpaceInvadersNoFrameskip-v4:
  env_wrapper:
    - stable_baselines3.common.atari_wrappers.AtariWrapper
  frame_stack: 4
  policy: 'CnnPolicy'
  n_timesteps: !!float 1e7
  buffer_size: 100000
  learning_rate: !!float 1e-4
  batch_size: 32
  learning_starts: 100000
  target_update_interval: 1000
  train_freq: 4
  gradient_steps: 1
  exploration_fraction: 0.1
  exploration_final_eps: 0.01
  # If True, you need to deactivate handle_timeout_termination
  # in the replay_buffer_kwargs
  optimize_memory_usage: False
```
